#!/bin/sh
### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    mountkernfs $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set up iptables rules
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

# Include config file for iptables-persistent
if [ -e /etc/iptables/iptables.conf ]
then
        . /etc/iptables/iptables.conf
fi

case "$1" in
start)
    if [ -e /var/run/iptables ]; then
        echo "iptables is already started!"
        exit 1
    else
        touch /var/run/iptables
    fi

    if [ $ENABLE_ROUTING -ne 0 ]; then
        # Enable Routing
        echo 1 > /proc/sys/net/ipv4/ip_forward
    fi

    # Load Modules
    [ -n "$MODULES" ] && modprobe -a $MODULES

    # Load saved rules
    if [ -f /etc/iptables/rules ]; then
        iptables-restore </etc/iptables/rules
    fi
    if [ -f /etc/iptables/rules6 ]; then
        ip6tables-restore </etc/iptables/rules6
    fi
    ;;
stop|force-stop)
    if [ ! -e /var/run/iptables ]; then
        echo "iptables is already stopped!"
        exit 1
    else
        rm /var/run/iptables
    fi

    if [ $SAVE_NEW_RULES -ne 0 ]; then
        # Backup old rules
        cp /etc/iptables/rules /etc/iptables/rules.bak
		cp /etc/iptables/rules6 /etc/iptables/rules6.bak
        # Save new rules
        iptables-save >/etc/iptables/rules
		ip6tables-save >/etc/iptables/rules6
    fi

    # Revert to Default Policy
    iptables -P INPUT ACCEPT
    iptables -P OUTPUT ACCEPT
    iptables -P FORWARD ACCEPT
    ip6tables -P INPUT ACCEPT
    ip6tables -P OUTPUT ACCEPT
    ip6tables -P FORWARD ACCEPT

    # Flush all rules and delete all custom chains
    iptables -F
    iptables -X
    ip6tables -F
    ip6tables -X

    for TABLE in filter nat mangle
    do
        iptables -t $TABLE -F
        iptables -t $TABLE -X
        iptables -t $TABLE -Z
        ip6tables -t $TABLE -F
        ip6tables -t $TABLE -X
        ip6tables -t $TABLE -Z
    done

    # Unload previously loaded modules
    [ -n "$MODULES" ] && modprobe -a $MODULES

    # Disable Routing if enabled
    if [ $ENABLE_ROUTING -ne 0 ]; then
        # Disable Routing
        echo 0 > /proc/sys/net/ipv4/ip_forward
    fi

    ;;
restart|force-reload)
    $0 stop
    $0 start
    ;;
status)
    echo "Filter Rules:"
    echo "--------------"
    iptables -L -v
    echo ""
    echo "NAT Rules:"
    echo "-------------"
    iptables -t nat -L -v
    echo ""
    echo "Mangle Rules:"
    echo "----------------"
    iptables -t mangle -L -v
    echo ""
    echo "Filter Rules IPv6:"
    echo "--------------"
    ip6tables -L -v
    echo ""
    echo "Mangle Rules IPv6:"
    echo "----------------"
    ip6tables -t mangle -L -v
    ;;
*)
    echo "Usage: $0 {start|stop|force-stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
