#!/bin/sh
#
# Gemeinschaft 5
# live-build auto config script
#
# Copyright (c) 2012, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GBE file for details.
#

lb config noauto \
	--apt apt \
	--apt-recommends disabled \
	--architecture i386 \
	--archive-areas "main" \
	--bootstrap-flavour minimal \
	--chroot-filesystem squashfs \
	--debian-installer live \
	--distribution squeeze \
	--hostname gs-live \
	--iso-application "Gemeinschaft 5" \
	--iso-preparer "Gemeinschaft Build Enrironment" \
	--iso-publisher "Amooma GmbH; http://www.amooma.de/" \
	--iso-volume "GS5" \
	--language en \
	--linux-flavours 686 \
	--memtest none \
	--mode debian \
	--packages-lists minimal \
	--root-command sudo \
	--syslinux-splash "config/binary_syslinux/splash.rle" \
	--syslinux-timeout 10 \
	--username gsmaster \
	--win32-loader disabled \
	--includes none \
	"${@}"
