#!/bin/bash

### BEGIN INIT INFO
# Provides:          gdfdl-custom-init
# Required-Start:    mysql
# Required-Stop:
# X-Start-Before:    apache2 freeswitch gdfdl-init
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Do initial task for first startup of Gemeinschaft
# Description:       
### END INIT INFO

# General settings
[ -f /gdfdl.conf ] && source /gdfdl.conf
[ -f /gdfdl-custom.conf ] && source /gdfdl-custom.conf
set -e

case "$1" in
	start)
		# Post-Installation setup for Gemeinschaft 5
		#

		echo -e "Preparing Gemeinschaft for 1st start ...\n"

		# Change primary group of GS system admin to GS_GROUP
		#
		set +e
		usermod -g ${GS_GROUP} gsmaster 2>&1 >/dev/null
		groupdel gsmaster 2>&1 >/dev/null
		set -e

		# Database setup
		#
		
		# Change MySQL password for user root
		if [ ! -f /root/.mysql_root_password ]
			then
			echo "** Generating individual password for MySQL user 'root'"
			apg -m30 -a0 -n 1 > /root/.mysql_root_password
			chmod 0440 /root/.mysql_root_password
			MYSQL_PASSWD_ROOT="`cat /root/.mysql_root_password`"
			mysql -e "USE mysql; DELETE FROM user WHERE user='root' AND NOT (host='localhost' OR host='127.0.0.1'); UPDATE user SET password=PASSWORD('${MYSQL_PASSWD_ROOT}') WHERE user='root' AND (host='localhost' OR host='127.0.0.1'); FLUSH PRIVILEGES;" --user=root --password="${MYSQL_PASSWD}"
		else
			MYSQL_PASSWD_ROOT="`cat /root/.mysql_root_password`"
		fi

		# FIXME: Hack in static password as long as it's hardcoded too much in the GS5 code...
		echo gemeinschaft > "/var/lib/${GS_USER}/.mysql_gs_password"

		# Create MySQL user for Gemeinschaft
		if [ ! -f "/var/lib/${GS_USER}/.mysql_gs_password" ]
			then
			echo "** Creating MySQL user 'gemeinschaft'"
			apg -m30 -a0 -n 1 > "/var/lib/${GS_USER}/.mysql_gs_password"
			chown ${GS_USER}.${GS_GROUP} "/var/lib/${GS_USER}/.mysql_gs_password"
			chmod 0440 "/var/lib/${GS_USER}/.mysql_gs_password"
			MYSQL_PASSWD_GS="`cat "/var/lib/${GS_USER}/.mysql_gs_password"`"
			mysql -e "GRANT ALL PRIVILEGES ON gemeinschaft.* TO gemeinschaft @'localhost' IDENTIFIED BY '${MYSQL_PASSWD_GS}'; FLUSH PRIVILEGES;" --user=root --password="${MYSQL_PASSWD_ROOT}"
		else
			MYSQL_PASSWD_GS="`cat "/var/lib/${GS_USER}/.mysql_gs_password"`"
		fi

		# Generate ODBC configuration files
		echo "** Configuring ODBC"
echo "[gemeinschaft]
Description  = MySQL database for Gemeinschaft
Driver       = /usr/lib/odbc/libmyodbc.so
Setup        = /usr/lib/odbc/libodbcmyS.so
" >/etc/odbcinst.ini

echo "[gemeinschaft]
Description  = MySQL database for Gemeinschaft
Driver       = /usr/lib/odbc/libmyodbc.so
SERVER       = localhost
PORT         = 3306
DATABASE     = gemeinschaft
OPTION       = 67108864
USER         = gemeinschaft
PASSWORD     = ${MYSQL_PASSWD_GS}
" >/etc/odbc.ini
		chmod 0640 /etc/odbc.ini

		# (re)create Gemeinschaft database
		echo "** Creating MySQL database 'gemeinschaft'"
		mysql -e "DROP DATABASE IF EXISTS gemeinschaft; CREATE DATABASE gemeinschaft;" --user=root --password="${MYSQL_PASSWD_ROOT}"

		# Update database password in Gemeinschaft config
		# FIXME: a lot of files are missing, conrete files still unknown !!!!!
		#
		echo "** Updating GS with new MySQL password"
		sed -i "s/password: gemeinschaft/password: ${MYSQL_PASSWD_GS}/" "${GS_DIR}/config/database.yml"

		# Load database structure into DB
		#
		echo "** Initializing database"
		su - ${GS_USER} -c "cd ${GS_DIR}; RAILS_ENV=production bundle exec rake db:migrate --trace 2>&1 >/var/log/gemeinschaft/init.log"

		# Generate assets (like CSS)
		#
		echo "** Precompile GS assets"
		su - ${GS_USER} -c "cd \"${GS_DIR}\"; RAILS_ENV=production bundle exec rake assets:precompile --trace 2>&1 >>/var/log/gemeinschaft/init.log"

		# self destruction
		#
		rm -rf /gdfdl-custom.conf
		rm -rf /etc/init.d/gdfdl-custom-init; update-rc.d gdfdl-custom-init remove
		;;

	stop)
		# nothing to do
		;;
	*)
		echo "Undefined usage."
		exit 3
		;;
esac
