#! /bin/bash
### BEGIN INIT INFO
# Provides:          gdfdl-prompt
# Required-Start:    $local_fs $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gemeinschaft Login screen
# Description:       
### END INIT INFO
#
# Create customized login screen for Gemeinschaft 5
#

IPS="`/bin/hostname -I`"
FQDN="`/bin/hostname -f`"
GDFDL_BUILDNAME="`cat /etc/gdfdl_build`"
GS_BRANCH="`cat /etc/gemeinschaft_branch`"

if [[ x`cat /proc/cmdline | grep boot=live` != x"" ]]
	then
	LIVE=true
else
	LIVE=false
fi

[ -f /etc/gdfdl_build ] && BUILD=`cat /etc/gdfdl_build` || BUILD=1234567890
if [[ `expr length ${BUILD}` == 10 ]]
	then
	PRODUCTION=true
else
	PRODUCTION=false
fi

[ -f /etc/gemeinschaft_release ] && BUILD=`cat /etc/gdfdl_build` || BUILD=1234567890
if [[ `expr length ${BUILD}` == 10 ]]
	then
	PRODUCTION=true
	VERSION=`cat /etc/gemeinschaft_release`
else
	PRODUCTION=false
	VERSION="5.0"
fi


echo "
***      _____                                               _____
***     (.---.)              GEMEINSCHAFT 5.0               (.---.)
***      /:::\\\ _.-----------------------------------------._ /:::\\\ 
***      -----                                               -----" > /etc/issue

if [[ ${PRODUCTION} == true ]]
	then
	echo "***     Release Version: ${VERSION}.${GDFDL_BUILDNAME}" >> /etc/issue
else
	echo "***     GS Branch: ${GS_BRANCH}, Build: ${GDFDL_BUILDNAME}" >> /etc/issue
fi

***    -------------------------------------------------------------
***
***     You have to configure Gemeinschaft with a web browser:
***" >> /etc/issue

if [[ -z "${IPS}" ]]; then
	echo "***     - FAILED network configuration detection -" >> /etc/issue
	echo "***" >> /etc/issue
else
	for ADDRESS in ${FQDN} ${IPS}
	do
		[[ ${ADDRESS} =~ "localhost" ]] && echo "***" >> /etc/issue && continue
		[[ ${ADDRESS} =~ ":" ]] && ADDRESS="["${ADDRESS}"]" 
		echo "***     http://${ADDRESS}" >> /etc/issue
	done
fi

echo "***
***" >> /etc/issue

if [[ ${LIVE} == true ]]
	then
	echo "***     DEMO LIVE SYSTEM - ALL CHANGES WILL BE LOST AFTER A REBOOT!" >> /etc/issue
	echo "***" >> /etc/issue
	echo "***     LOGIN   : gsmaster" >> /etc/issue
    echo "***     PASSWORD: `cat /home/gsmaster/.password`" >> /etc/issue
else
	echo "***" >> /etc/issue
	echo "***" >> /etc/issue
	echo "***" >> /etc/issue
	echo "***" >> /etc/issue
fi

echo "***
***    _____________________________________________________________
***          brought to you by AMOOMA GmbH  - http://amooma.de
" >> /etc/issue
