#!/bin/bash

### BEGIN INIT INFO
# Provides:          gdfdl-custom-init
# Required-Start:    mysql
# Required-Stop:
# X-Start-Before:    apache2 freeswitch gdfdl-init
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Do initial task for first startup of Gemeinschaft
# Description:       
### END INIT INFO

# General settings
[ -f /gdfdl.conf ] && source /gdfdl.conf
[ -f /gdfdl-custom.conf ] && source /gdfdl-custom.conf
set -e

case "$1" in
	start)
		# Post-Installation setup for Gemeinschaft 5
		#

		echo -e "Preparing Gemeinschaft for 1st start ...\n"

		# Change primary group of GS system admin to GS_GROUP
		#
		usermod -g ${GS_GROUP} gsmaster

		# Database setup
		#
		
		# let root administer mysql without password when connecting through localhost
		mysql -e "USE mysql; DELETE FROM user WHERE user='root' AND NOT (host='localhost' OR host='127.0.0.1'); UPDATE user SET password=null WHERE user='root' AND (host='localhost' OR host='127.0.0.1');" --user=root --password=$MYSQL_PASSWD
		mysql -e "GRANT ALL PRIVILEGES ON gemeinschaft.* TO gemeinschaft @'localhost' IDENTIFIED BY 'gemeinschaft';"
		mysql -e "FLUSH PRIVILEGES"

		mysql -e "DROP DATABASE IF EXISTS gemeinschaft;"
		mysql -e "CREATE DATABASE gemeinschaft;"

echo "[gemeinschaft]
Description  = MySQL database for Gemeinschaft
Driver       = /usr/lib/odbc/libmyodbc.so
Setup        = /usr/lib/odbc/libodbcmyS.so
" >/etc/odbcinst.ini

echo "[gemeinschaft]
Description  = MySQL database for Gemeinschaft
Driver       = /usr/lib/odbc/libmyodbc.so
SERVER       = localhost
PORT         = 3306
DATABASE     = gemeinschaft
OPTION       = 67108864
USER         = gemeinschaft
PASSWORD     = gemeinschaft
" >/etc/odbc.ini

		# Load database structure into DB
		#
		su - ${GS_USER} -c "cd ${GS_DIR}; RAILS_ENV=production bundle exec rake db:migrate --trace 2>&1 >~/gs5-init.log"

		# Generate CSS
		#
		su - ${GS_USER} -c "cd \"${GS_DIR}\"; RAILS_ENV=production bundle exec rake assets:precompile --trace 2>&1 >>~/gs5-init.log"

		# self destruction
		#
		rm -rf /gdfdl-custom.conf
		rm -rf /etc/init.d/gdfdl-custom-init; update-rc.d gdfdl-custom-init remove
		;;

	stop)
		# nothing to do
		;;
	*)
		echo "Undefined usage."
		exit 3
		;;
esac
