#! /bin/bash
### BEGIN INIT INFO
# Provides:          gdfdl-prompt
# Required-Start:    $local_fs $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gemeinschaft Login screen
# Description:       
### END INIT INFO
#
# Create customized login screen for Gemeinschaft 5
#

IPS="`/bin/hostname -I`"
FQDN="`/bin/hostname -f`"
GDFDL_BUILDNAME="`cat /etc/gdfdl_build`"
GS_BRANCH="`cat /etc/gemeinschaft_branch`"

if [[ x`cat /proc/cmdline | grep boot=live` != x"" ]]
	then
	LIVE=true
else
	LIVE=false
fi

echo "
***      _____                                               _____
***     (.---.)                GEMEINSCHAFT 5               (.---.)
***      /:::\\\ _.-----------------------------------------._ /:::\\\ 
***      -----                                               -----
***     Branch: ${GS_BRANCH}, Build: ${GDFDL_BUILDNAME}
***     Hostname: \n Console: \l
***    -------------------------------------------------------------
***
***     You can reach the web configuration here:
***" > /etc/issue

for ADDRESS in ${FQDN} ${IPS}
do
	[[ ${ADDRESS} =~ "localhost" ]] && echo "***" && continue
	[[ ${ADDRESS} =~ ":" ]] && ADDRESS="["${ADDRESS}"]" 
	echo "***     http://${ADDRESS}/" >> /etc/issue
done

echo "***
***
***" >> /etc/issue

if [[ ${LIVE} == true ]]
	then
	echo "***     LIVE SYSTEM - ALL CHANGES WILL BE LOST AFTER REBOOT" >> /etc/issue
else
	echo "***" >> /etc/issue
fi

echo "***
***
***
***
***    _____________________________________________________________
***     brought to you by AMOOMA - http://www.amooma.de/
" >> /etc/issue
