#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-runtime-init
# Required-Start:    hostname
# Required-Stop:     
# X-Start-Before:    apache2
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Updates certain configurations after reboot
# Description:       Updates certain configurations after reboot to comply with current network settings
### END INIT INFO

# General settings
[ -f /etc/gemeinschaft/system.conf ] && source /etc/gemeinschaft/system.conf || echo "FATAL ERROR: Local configuration file in /etc/gemeinschaft/system.conf missing"

case "$1" in
start)
	FQDN="`hostname -f`";
	IPS="`hostname -I`"

	# Create SSL certificate for current Full Qualified Domain Name
	if [[
		! -f /etc/ssl/private/${FQDN}.key ||
		! -f /etc/ssl/certs/${FQDN}.crt
		]]; then

		# Make sure both files are not existing
		rm -rf /etc/ssl/private/${FQDN}.key /etc/ssl/certs/${FQDN}.crt

		echo "Generating SSL certificate for ${FQDN} ..."
		openssl req -newkey rsa:2048 -x509 -days 3650 -nodes -out /etc/ssl/certs/${FQDN}.crt -keyout /etc/ssl/private/${FQDN}.key -subj "/C=DE/ST=Rhineland-Palatinate/L=Neuwied/O=AMOOMA GmbH/OU=Self-generated certificate for Gemeinschaft/CN=${FQDN}"
		update-ca-certificates

		ln -sf /etc/ssl/private/${FQDN}.key /etc/ssl/gemeinschaft.key
		ln -sf /etc/ssl/certs/${FQDN}.crt /etc/ssl/gemeinschaft.crt
	fi

	;;
*)
	# nothing to do
	;;
esac
