#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-runtime-init-post
# Required-Start:    hostname $local_fs $all
# Required-Stop:     
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Updates certain configurations after reboot
# Description:       Updates certain configurations after reboot to comply with current network settings
### END INIT INFO


case "$1" in
start)
	IPS="`hostname -I`"

	# Update dnsmasq configuration with current IPv4 address for auto-provisioning
	for ADDRESS in ${IPS}
	do
		[[ ${ADDRESS} =~ ":" ]] && continue
		echo "Updating DNSmasq configurations ..."
		if [[ -f /etc/dnsmasq.d/gs_phone_vendors.conf ]]; then
			sed -i "s/^dhcp-option=SNOM,66.*\$/dhcp-option=SNOM,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=net:OpenStage,vendor:OptiIpPhone,3.*\$/dhcp-option=net:OpenStage,vendor:OptiIpPhone,3,\"sdlp:\/\/${ADDRESS}:443\"/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=POLYCOM,66.*\$/dhcp-option=POLYCOM,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
		fi
		if [[ -f /etc/dnsmasq.d/gemeinschaft_simple.conf ]]; then
			sed -i "s/^#dhcp-range=.*proxy.*\$/#dhcp-range=${ADDRESS},proxy/" /etc/dnsmasq.d/gemeinschaft_simple.conf
		fi
		/etc/init.d/dnsmasq restart
	done

	# Update Gemeinschaft config with current IPv4 address
	for ADDRESS in ${IPS}
	do
		[[ ${ADDRESS} =~ ":" ]] && continue

		echo "Updating Gemeinschaft configurations ..."

		# Update static files
		[[ -f /opt/gemeinschaft/misc/freeswitch/scripts/ini/dialplan.ini ]] && sed -i "s/^phone_book_entry_image_url =.*/phone_book_entry_image_url = http:\/\/${ADDRESS}\/uploads\/phone_book_entry\/image/" /opt/gemeinschaft/misc/freeswitch/scripts/ini/dialplan.ini
		[[ -f /opt/gemeinschaft/misc/freeswitch/scripts/ini/dialplan.ini ]] && sed -i "s/^user_image_url =.*/user_image_url = http:\/\/${ADDRESS}\/uploads\/user\/image/" /opt/gemeinschaft/misc/freeswitch/scripts/ini/dialplan.ini
		[[ -f /opt/gemeinschaft/misc/freeswitch/scripts/ini/dialplan.ini ]] && sed -i "s/^ringtone_url =.*/ringtone_url = http:\/\/${ADDRESS}/" /opt/gemeinschaft/misc/freeswitch/scripts/ini/dialplan.ini

		# Update database settings
		if [ -f /var/lib/gs5/.gs_mysql_password ];
			then
				MYSQL_PASSWD="`cat /var/lib/gs5/.gs_mysql_password`"
				mysql -e "UPDATE gs_parameters SET value = '127.0.0.1' WHERE name = 'HOMEBASE_IP_ADDRESS';" --user=gemeinschaft --password="${MYSQL_PASSWD}" gemeinschaft
		else
			echo "ERROR: GS lost it's database password in /var/lib/gs5/.gs_mysql_password !"
		fi



	done

	;;
*)
	# nothing to do
	;;
esac
