#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-runtime-init
# Required-Start:    hostname
# Required-Stop:     
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Updates certain configurations after reboot
# Description:       Updates certain configurations after reboot to comply with current network settings
### END INIT INFO


case "$1" in
start)
	FQDN="`hostname -f`";
	IPS="`hostname -I`"

	# Create SSL certificate for current Full Qualified Domain Name
	if [[
		! -f /etc/ssl/private/${FQDN}.key ||
		! -f /etc/ssl/certs/${FQDN}.crt
		]]; then

		# Make sure both files are not existing
		rm -rf /etc/ssl/private/${FQDN}.key /etc/ssl/certs/${FQDN}.crt

		echo "Generating SSL certificate for ${FQDN} ..."
		openssl req -newkey rsa:2048 -x509 -days 3650 -nodes -out /etc/ssl/certs/${FQDN}.crt -keyout /etc/ssl/private/${FQDN}.key -subj "/C=DE/ST=Rhineland-Palatinate/L=Neuwied/O=AMOOMA GmbH/OU=Self-generated certificate for Gemeinschaft/CN=${FQDN}"
		update-ca-certificates

		ln -sf /etc/ssl/private/${FQDN}.key /etc/ssl/gemeinschaft.key
		ln -sf /etc/ssl/certs/${FQDN}.crt /etc/ssl/gemeinschaft.crt
		
		/etc/init.d/apache2 reload
		/etc/init.d/postfix reload
	fi

	# Update dnsmasq configuration with current IPv4 address for auto-provisioning
	for ADDRESS in ${IPS}
	do
		[[ ${ADDRESS} =~ ":" ]] && continue
		echo "Updating DNSmasq configurations ..."
		if [[ -f /etc/dnsmasq.d/gs_phone_vendors.conf ]]; then
			sed -i "s/^dhcp-option=SNOM,66.*\$/dhcp-option=SNOM,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=SEC1,66.*\$/dhcp-option=SEC1,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=SEC2,66.*\$/dhcp-option=SEC2,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=POLYCOM,66.*\$/dhcp-option=POLYCOM,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
		fi
		if [[ -f /etc/dnsmasq.d/gemeinschaft_simple.conf ]]; then
			sed -i "s/^#dhcp-range=.*proxy.*\$/#dhcp-range=${ADDRESS},proxy/" /etc/dnsmasq.d/gemeinschaft_simple.conf
		fi
		/etc/init.d/dnsmasq restart
	done

	;;
*)
	# nothing to do
	;;
esac
