#! /bin/bash
### BEGIN INIT INFO
# Provides:          gemeinschaft-runtime-init-post
# Required-Start:    hostname $local_fs $all
# Required-Stop:     
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Updates certain configurations after reboot
# Description:       Updates certain configurations after reboot to comply with current network settings
### END INIT INFO


case "$1" in
start)
	IPS="`hostname -I`"

	# Update dnsmasq configuration with current IPv4 address for auto-provisioning
	for ADDRESS in ${IPS}
	do
		[[ ${ADDRESS} =~ ":" ]] && continue
		echo "Updating DNSmasq configurations ..."
		if [[ -f /etc/dnsmasq.d/gs_phone_vendors.conf ]]; then
			sed -i "s/^dhcp-option=SNOM,66.*\$/dhcp-option=SNOM,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=SEC1,66.*\$/dhcp-option=SEC1,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=SEC2,66.*\$/dhcp-option=SEC2,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
			sed -i "s/^dhcp-option=POLYCOM,66.*\$/dhcp-option=POLYCOM,66,https:\/\/${ADDRESS}:443/" /etc/dnsmasq.d/gs_phone_vendors.conf
		fi
		if [[ -f /etc/dnsmasq.d/gemeinschaft_simple.conf ]]; then
			sed -i "s/^#dhcp-range=.*proxy.*\$/#dhcp-range=${ADDRESS},proxy/" /etc/dnsmasq.d/gemeinschaft_simple.conf
		fi
		/etc/init.d/dnsmasq restart
	done

	# Update Gemeinschaft config with current IPv4 address
	for ADDRESS in ${IPS}
	do
		[[ ${ADDRESS} =~ ":" ]] && continue
		echo "Updating Gemeinschaft configurations ..."
		if [[ -f /opt/gemeinschaft/config/initializers/gemeinschaft_parameters.rb ]]; then
			sed -i "s/^HOMEBASE_IP_ADDRESS =.*/HOMEBASE_IP_ADDRESS = '${ADDRESS}'/" /opt/gemeinschaft/config/initializers/gemeinschaft_parameters.rb
		fi
	done

	;;
*)
	# nothing to do
	;;
esac
