#! /bin/bash
### BEGIN INIT INFO
# Provides:          gs-ssl
# Required-Start:    hostname
# Required-Stop:     
# X-Start-Before:    apache2
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Generate SSL certificates for current hostname
# Description:       
### END INIT INFO


case "$1" in
start)
	HOSTNAME="`hostname -f`";

	if [[
		! -f /etc/ssl/private/${HOSTNAME}.key ||
		! -f /etc/ssl/certs/${HOSTNAME}.crt
		]]; then

		# Make sure both files are not existing
		rm -rf /etc/ssl/private/${HOSTNAME}.key /etc/ssl/certs/${HOSTNAME}.crt

		echo "Generating SSL certificate for ${HOSTNAME} ..."
		openssl req -newkey rsa:2048 -x509 -days 3650 -nodes -out /etc/ssl/certs/${HOSTNAME}.crt -keyout /etc/ssl/private/${HOSTNAME}.key -subj "/C=DE/ST=Rhineland-Palatinate/L=Neuwied/O=AMOOMA GmbH/OU=Self-generated certificate for Gemeinschaft/CN=${HOSTNAME}"

		ln -sf /etc/ssl/private/${HOSTNAME}.key /etc/ssl/gemeinschaft.key
		ln -sf /etc/ssl/certs/${HOSTNAME}.crt /etc/ssl/gemeinschaft.crt
	fi
	;;
*)
	# nothing to do
	;;
esac
