#!/bin/bash
#
# Gemeinschaft 5
# live-build auto config script
#
# Copyright (c) 2012-2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GBE file for details.
#

. /etc/environment

if [ x"${http_proxy}" != x"" ]; then

	echo "http_proxy environment variable found - configuring LB to use it"

lb config noauto \
	--apt-http-proxy ${http_proxy} \
	--apt apt \
	--apt-indices false \
	--apt-recommends false \
	--architecture i386 \
	--archive-areas "main contrib non-free" \
	--chroot-filesystem squashfs \
	--debian-installer live \
	--debootstrap-options "--variant=minbase" \
	--iso-application "Gemeinschaft 5" \
	--iso-preparer "Gemeinschaft Build Environment" \
	--iso-publisher "AMOOMA GmbH; http://amooma.de/" \
	--iso-volume "GS5" \
	--linux-flavours "486 686-pae" \
	--memtest none \
	--mode debian \
	--root-command sudo \
	--win32-loader disabled \
	"${@}"

else

lb config noauto \
	--apt apt \
	--apt-indices false \
	--apt-recommends false \
	--architecture i386 \
	--archive-areas "main contrib non-free" \
	--chroot-filesystem squashfs \
	--debian-installer live \
	--debootstrap-options "--variant=minbase" \
	--iso-application "Gemeinschaft 5" \
	--iso-preparer "Gemeinschaft Build Environment" \
	--iso-publisher "AMOOMA GmbH; http://amooma.de/" \
	--iso-volume "GS5" \
	--linux-flavours "486 686-pae" \
	--memtest none \
	--mode debian \
	--root-command sudo \
	--win32-loader disabled \
	"${@}"
fi
