#!/bin/bash
#
# Gemeinschaft 5
# live-build auto config script
#
# Copyright (c) 2012, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GBE file for details.
#

lb config noauto \
	--apt apt \
	--apt-recommends disabled \
	--architecture i386 \
	--archive-areas "main" \
	--chroot-filesystem squashfs \
	--debian-installer live \
	--iso-application "Gemeinschaft 5" \
	--iso-preparer "Gemeinschaft Build Environment" \
	--iso-publisher "AMOOMA GmbH; http://www.amooma.de/" \
	--iso-volume "GS5" \
	--linux-flavours 686 \
	--memtest none \
	--mode debian \
	--root-command sudo \
	--win32-loader disabled \
	"${@}"
